stages:
  prepare:
    cmd: poetry run python nudging/prepare.py
    deps:
    - data/external
    - nudging/prepare.py
    - nudging/propensity_score.py
    - nudging/utils.py
    - nudging/reader
    outs:
    - data/interim
    - data/raw
  train:
    cmd: poetry run python nudging/train.py
    deps:
    - data/interim
    - nudging/train.py
    - nudging/utils.py
    outs:
    - models
  predict:
    cmd: poetry run python nudging/predict.py
    deps:
    - data/interim
    - models
    - nudging/predict.py
    - nudging/utils.py
    outs:
    - data/processed
    - plots
