stages:
  prepare:
    cmd: poetry run python src/prepare.py
    deps:
    - data/external
    - src/prepare.py
    outs:
    - data/interim
    - data/raw
  train:
    cmd: poetry run python src/train.py
    deps:
    - data/interim
    - src/train.py
    outs:
    - models
  predict:
    cmd: poetry run python src/predict.py
    deps:
    - data/interim
    - models
    - src/predict.py
    outs:
    - data/processed
