stages:
  prepare:
    cmd: poetry run python src/nudge_success.py
    deps:
    - data/external
    - src/nudge_success.py
    outs:
    - data/interim
    - data/raw
  train:
    cmd: poetry run python src/nudge_probability.py
    deps:
    - data/interim
    - src/nudge_probability.py
    outs:
    - data/processed
