# Run pylint and pytest
name: Build-Lint-Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint pytest
          python -m pip install .

      - name: Pylint
        run: pylint nudging

      - name: Pytest  
        run: pytest tests
